global using DeepSpaceSaga.Universe;
global using DeepSpaceSaga.Tools;
global using DeepSpaceSaga.Common.Tools;
global using DeepSpaceSaga.Common.Universe.Entities.CelestialObjects;
global using DeepSpaceSaga.Common.Universe.Entities.CelestialObjects.Spacecrafts;
global using DeepSpaceSaga.Common.Universe;
global using DeepSpaceSaga.Common.Universe.Equipment;
global using DeepSpaceSaga.Common.Universe.Equipment.Propulsion;
global using DeepSpaceSaga.Server.Generation.Modules;