global using DeepSpaceSaga.Common.Extensions;
global using DeepSpaceSaga.Common.Tools.ArrayExtensions;
global using DeepSpaceSaga.Common.Universe;
global using DeepSpaceSaga.Common.Universe.Entities.CelestialObjects;
global using System.Drawing;
global using System.Reflection;
global using System.Numerics;
global using DeepSpaceSaga.Universe;
global using DeepSpaceSaga.Common.Universe.Entities.CelestialObjects.Spacecrafts;
